// money-exchange-vue/src/components/ComboBox.vue
<template>
  <Popover v-model:open="open">
    <PopoverTrigger as-child>
      <Button
        variant="outline"
        role="combobox"
        :aria-expanded="open"
        class="w-[200px] justify-between overflow-hidden"
      >
        {{ selectedValue }}
      </Button>
    </PopoverTrigger>
    <PopoverContent class="w-[200px] p-0">
      <Command>
        <CommandInput v-model="search" placeholder="Search option..." />
        <CommandEmpty>No option found.</CommandEmpty>
        <CommandGroup :key="search">
          <CommandItem
            v-for="option in options"
            :key="option.value"
            :value="option.value"
            @select="handleSelect(option)"
          >
            {{ option.label }}
          </CommandItem>
        </CommandGroup>
      </Command>
    </PopoverContent>
  </Popover>
</template>

<script setup lang="ts">
import { ref, computed, nextTick } from 'vue';
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
} from '@/components/ui/command';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import { Button } from '@/components/ui/button';

interface Option {
  label: string;
  value: string;
}

interface Props {
  selected?: Option;
  options: Option[];
}

interface Emits {
  (e: 'update:selected', value: Option): void;
}

const props = withDefaults(defineProps<Props>(), {
  selected: undefined
});

const emit = defineEmits<Emits>();

const open = ref<boolean>(false);
const search = ref<string>("");

const selected = defineModel<Option>('selected');

const selectedValue = computed(() => 
  props.options.find((f) => f.value === selected.value?.value)?.label ?? "Select a option..."
);

// We want to refocus the trigger button when the user selects
// an item from the list so users can continue navigating the
// rest of the form with the keyboard.
function closeAndFocusTrigger(triggerId: string) {
  open.value = false;
  nextTick(() => {
    document.getElementById(triggerId)?.focus();
  });
}

function handleSelect(option: Option) {
  selected.value = option;
  emit('update:selected', option);
  open.value = false;
}
</script>

// money-exchange-svelte/src/lib/components/ComboBox.svelte
<script lang="ts">
 import { tick } from "svelte";
 import * as Command from "$lib/components/ui/command/index.js";
 import * as Popover from "$lib/components/ui/popover/index.js";
 import { Button } from "$lib/components/ui/button/index.js";
 import { cn } from "$lib/utils.js";
 
 let { selected = $bindable(), options } = $props<{
  selected?: string;
  options: { label: string; value: string }[]; }>();

 let open = $state(false);
 
 let selectedValue = $derived(options.find((f) => f.value === selected.value)?.label ?? "Select a option...");
  
 
 // We want to refocus the trigger button when the user selects
 // an item from the list so users can continue navigating the
 // rest of the form with the keyboard.
 function closeAndFocusTrigger(triggerId: string) {
  open = false;
  tick().then(() => {
   document.getElementById(triggerId)?.focus();
  });
 }
 let search = $state("");
</script>
 
<Popover.Root bind:open let:ids>
 <Popover.Trigger asChild let:builder>
  <Button
   builders={[builder]}
   variant="outline"
   role="combobox"
   aria-expanded={open}
   class="w-[200px] justify-between overflow-hidden"
  >
   {selectedValue}
  </Button>
 </Popover.Trigger>
 <Popover.Content class="w-[200px] p-0">
  <Command.Root>
   <Command.Input placeholder="Search option..." bind:value={search}/>
   <Command.Empty>No option found.</Command.Empty>
   {#key search}
    <Command.Group>
        {#each options as option}
        <Command.Item
            value={option.value}
            onSelect={(currentValue) => {
            selected = option;
            closeAndFocusTrigger(ids.trigger);
            }}
        >
        {option.label}
        </Command.Item>
        {/each}
    </Command.Group>
    {/key}
  </Command.Root>
 </Popover.Content>
</Popover.Root>
